import requests
import threading

while True:
    x = input(" ██▓███   ▒█████   ██▓     ██▓▄▄▄█████▓ ██▀███  ▓██   ██▓\n▓██░  ██▒▒██▒  ██▒▓██▒    ▓██▒▓  ██▒ ▓▒▓██ ▒ ██▒ ▒██  ██▒\n▓██░ ██▓▒▒██░  ██▒▒██░    ▒██▒▒ ▓██░ ▒░▓██ ░▄█ ▒  ▒██ ██░\n▒██▄█▓▒ ▒▒██   ██░▒██░    ░██░░ ▓██▓ ░ ▒██▀▀█▄    ░ ▐██▓░\n▒██▒ ░  ░░ ████▓▒░░██████▒░██░  ▒██▒ ░ ░██▓ ▒██▒  ░ ██▒▓░\n▒▓▒░ ░  ░░ ▒░▒░▒░ ░ ▒░▓  ░░▓    ▒ ░░   ░ ▒▓ ░▒▓░   ██▒▒▒ \n░▒ ░       ░ ▒ ▒░ ░ ░ ▒  ░ ▒ ░    ░      ░▒ ░ ▒░ ▓██ ░▒░ \n░░       ░ ░ ░ ▒    ░ ░    ▒ ░  ░        ░░   ░  ▒ ▒ ░░  \n             ░ ░      ░  ░ ░              ░      ░ ░      \n\nType Here ur Username :")
                  # ^ username here
    def check_url(url):
        try:
            response = requests.get(url, timeout=5)
            if response.status_code == 200:
                with open("success_urls.txt", "a") as success_file:
                    success_file.write(url + "\n")
                print(f"{url} is up and running")
            else:
                print(f"{url} returned a status code of {response.status_code}")
        except requests.exceptions.RequestException as e:
            print(f"{url} caused an exception: {e}")

    proxies = {
    "http": "http://92.118.232.74:80",  #u need Proxy http
   #"http": "http://IP:Port",
    }

    response = requests.get("http://example.com", proxies=proxies)
    print(response.text)


    urls= {
    'http://forum.3dnews.ru/member.php?x=' + x,
    'https://albicla.com/' + x + '/post/1',
    'https://www.alltrails.com/members/' + x,
    'https://www.anime-planet.com/users/' + x,
    'https://api.anobii.com/users/eid/' + x,
    'https://apex.tracker.gg/apex/profile/origin/' + x + '/overview',
    'https://community.appian.com/members/' + x,
    'https://archiveofourown.org/users/' + x,
    'https://create.arduino.cc/projecthub/' + x,
    'https://ask.fm/' + x,
    'https://community.avid.com/members/' + x + '/default.aspx',
    'https://www.bandlab.com/api/v1.3/users/' + x,
    'https://www.bandlab.com/' + x,
    'https://' + x + '.bdsmlr.com',
    'https://www.bdsmsingles.com/members/' + x,
    'https://bentbox.co/' + x,
    'https://bitcoinforum.com/profile/' + x,
    'https://www.blogi.pl/osoba,' + x + '.html',
    'http://blogmarks.net/user/' + x,
    'http://' + x + '.blogspot.com',
    'http://api.bodybuilding.com/api-proxy/bbc/get?slug=' + x,
    'http://bodyspace.bodybuilding.com/' + x,
    'https://' + x + '.booth.pm/',
    'https://www.castingcall.club/' + x,
    'https://profile.cheezburger.com/' + x,
    'https://www.chess.com/member/' + x,
    'https://www.colourlovers.com/lover/' + x,
    'https://www.contactossex.com/profile/' + x,
    'https://www.datezone.com/users/' + x,
    'https://dating.ru/' + x,
    'https://www.designspiration.com/' + x,
    'https://www.deviantart.com/' + x,
    'https://devrant.com/users/' + x,
    'https://www.diigo.com/interact_api/load_profile_info?name=' + x,
    'https://www.diigo.com/profile/' + x,
    'https://www.discogs.com/user/' + x,
    'https://meta.discourse.org/u/' + x,
    'https://easyen.ru/index/8-0-' + x,
    'https://www.ebay.com/usr/' + x,
    'https://faktopedia.pl/user/' + x,
    'https://fancentro.com/api/profile.get?profileAlias='+ x +'&limit=1',
    'https://www.fandom.com/u/' + x,
    'https://www.fanpop.com/fans/' + x,
    'https://www.fark.com/users/' + x,
    'https://apiv2.fansly.com/api/v1/account?usernames=' + x,
    'https://www.fatsecret.com/member/' + x,
    'https://www.filmweb.pl/user/' + x,
    'https://www.fiverr.com/' + x,
    'https://www.flickr.com/photos/' + x,
    'https://www.fodors.com/community/profile/'+ x +'/forum-activity',
    'https://fortnitetracker.com/profile/all/' + x,
    'https://forumprawne.org/members/'+ x +'.html',
    'https://api.fotka.com/v2/user/dataStatic?login=' + x,
    'https://fotka.com/profil/' + x,
    'https://foursquare.com/' + x,
    'https://www.freelancer.com/u/' + x,
    'https://freesound.org/people/' + x,
    'https://friendfinder.com/profile/' + x,
    'https://www.friendfinder-x.com/profile/' + x,
    'https://friendweb.nl/' + x,
    'https://www.furaffinity.net/user/' + x,
    'https://gab.com/api/v1/account_by_username/' + x,
    'https://gab.com/' + x,
    'https://www.gamespot.com/profile/' + x,
    'https://connect.garmin.com/modern/profile/' + x,
    'https://www.geocaching.com/p/?u=' + x,
    'https://api.gettr.com/s/user/'+ x +'/exist',
    'https://giphy.com/channel/' + x,
    'http://www.girlfriendsmeet.com/profile/' + x,
    'https://github.com/' + x,
    'https://gitlab.com/' + x,
    'https://gitee.com/' + x,
    'https://gloria.tv/' + x,
    'https://gpodder.net/user/' + x,
    'https://grandprof.org/communaute/' + x,
    'http://en.gravatar.com/profiles/'+ x +'.json',
    'http://en.gravatar.com/profiles/' + x,
    'https://'+ x +'.gumroad.com/',
    'https://hackaday.io/' + x,
    'https://news.ycombinator.com/user?id=' + x,
    'https://hackernoon.com/_next/data/foL6JC7ro2FEEMD-gMKgQ/u/'+ x +'.json',
    'https://hackernoon.com/u/' + x,
    'https://hackerone.com/' + x,
    'https://www.hackster.io/' + x,
    'https://hamaha.net/' + x,
    'https://heylink.me/' + x,
    'https://www.houzz.com/user/' + x,
    'https://hubski.com/user/' + x,
    'https://www.iconfinder.com/' + x,
    'https://icq.icqchat.co/members/' + x,
    'https://ifttt.com/p/' + x,
    'http://forum.igromania.ru/member.php?username=' + x,
    'https://support.ilovegrowingmarijuana.com/u/' + x,
    'https://www.imagefap.com/profile/' + x,
    'https://imageshack.com/user/' + x,
    'https://imgsrc.ru/main/user.php?lang=ru&user=' + x,
    'https://api.imgur.com/account/v1/accounts/'+ x +'?client_id=546c25a59c58ad7&include=trophies%2Cmedallions',
    'https://imgur.com/user/'+ x +'/about',
    'https://independent.academia.edu/' + x,
    'https://inkbunny.net/' + x,
    'https://'+ x +'.insanejournal.com/profile',
    'https://instagram.com/' + x,
    'https://www.picuki.com/profile/' + x,
    'https://www.instructables.com/member/' + x,
    'https://archive.org/search.php?query=' + x,
    'https://www.interpals.net/' + x,
    'https://issuu.com/' + x,
    'https://www.jeja.pl/user,' + x,
    'https://jbzd.com.pl/uzytkownik/' + x,
    'https://www.jeuxvideo.com/profil/'+ x +'?mode=infos',
    'https://joemonster.org/bojownik/' + x,
    'https://jsfiddle.net/user/' + x,
    'https://justfor.fans/' + x,
    'https://www.kaggle.com/' + x,
    'https://karab.in/u/' + x,
    'https://keybase.io/' + x,
    'https://www.kickstarter.com/profile/' + x,
    'https://ws2.kik.com/user/' + x,
    'https://ko-fi.com/' + x,
    'https://www.kongregate.com/accounts/' + x,
    'https://kotburger.pl/user' + x,
    'https://kwejk.pl/uzytkownik/'+ x +'#/tablica/',
    'https://www.librarything.com/profile/' + x,
    'https://linktr.ee/' + x,
    'https://www.linux.org.ru/people/'+ x +'/profile',
    'https://'+ x +'.livejournal.com',
    'https://lobste.rs/u/' + x,
    'https://bazar.lowcygier.pl/user/' + x,
    'https://www.magix.info/us/users/profile/' + x,
    'https://www.mapmytracks.com/' + x,
    'https://marshmallow-qa.com/' + x,
    'https://martech.org/author/' + x,
    'https://www.massageanywhere.com/profile/' + x,
    'https://playerdb.co/api/player/minecraft/' + x,
    'https://mcuuid.net/?q=' + x,
    'https://'+ x +'.medium.com/about',
    'http://medyczka.pl/user/' + x,
    'https://www.meetme.com/' + x,
    'http://megamodels.pl/' + x,
    'https://social.technet.microsoft.com/profile/' + x,
    'https://www.minds.com/' + x,
    'https://minecraftlist.com/players/' + x,
    'https://mistrzowie.org/user/' + x,
    'https://mix.com/' + x,
    'https://mixi.jp/view_community.pl?id=' + x,
    'http://api.mixlr.com/users/' + x,
    'http://mixlr.com/' + x,
    'https://forums.mmorpg.com/profile/' + x,
    'https://www.moddb.com/members/' + x,
    'https://forums.moneysavingexpert.com/profile/' + x,
    'https://mklr.pl/user/' + x,
    'https://muckrack.com/' + x,
    'https://myanimelist.net/profile/' + x,
    'https://www.mybuilder.com/profile/view/' + x,
    'https://mym.fans/' + x,
    'https://myspace.com/' + x,
    'https://namemc.com/search?q=' + x,
    'https://www.nairaland.com/' + x,
    'https://naturalnews.com/author/' + x,
    'https://blog.naver.com/' + x,
    'https://www.netvibes.com/' + x,
    'https://'+ x +'.newgrounds.com/',
    'https://www.newmeet.com/en/profile/' + x,
    'https://notabug.org/' + x,
    'https://oglaszamy24h.pl/profil,' + x,
    'https://ok.ru/' + x,
    'https://www.olx.pl/oferty/uzytkownik/' + x,
    'https://osu.ppy.sh/users/' + x,
    'http://ow.ly/user/' + x,
    'https://pastebin.com/u/' + x,
    'https://www.patientslikeme.com/members/' + x,
    'https://www.patreon.com/' + x,
    'https://patronite.pl/' + x,
    'https://forums.pcgamer.com/members/' + x,
    'https://pcpartpicker.com/user/' + x,
    'https://retro.pewex.pl/user/' + x,
    'https://www.pinterest.com/' + x,
    'https://psnprofiles.com/xhr/search/users?q=' + x,
    'https://www.pornhub.com/users/' + x,
    'https://www.reddit.com/user/'+ x +'/about/.json',
    'https://www.reddit.com/user/' + x,
    'https://auth.roblox.com/v1/usernames/validate?username='+ x +'&birthday=2019-12-31T23:00:00.000Z',
    'https://rumble.com/c/' + x,
    'https://www.skypli.com/profile/' + x,
    'https://feelinsonice.appspot.com/web/deeplink/snapcode?username='+ x +'&size=400&type=SVG',
    'https://www.snapchat.com/add/' + x,
    'https://story.snapchat.com/s/' + x,
    'https://soundcloud.com/' + x,
    'https://sourceforge.net/u/'+ x +'/profile',
    'https://open.spotify.com/user/' + x,
    'https://steamcommunity.com/id/' + x,
    'https://stripchat.com/' + x,
    'https://t.me/' + x,
    'https://tellonym.me/' + x,
    'http://www.tf2items.com/id/' + x,
    'https://www.tiktok.com/@'+ x +'?lang=en',
    'https://tinder.com/@' + x,
    'https://'+ x +'.tumblr.com',
    'https://twitchtracker.com/search?q=' + x,
    'https://twitch.tv/' + x,
    'https://nitter.net/' + x,
    'https://twitter.com/' + x,
    'http://archive.org/wayback/available?url=https://twitter.com/' + x,
    'https://web.archive.org/web/2/https://twitter.com/' + x,
    'http://archive.org/wayback/available?url=https://twitter.com/'+ x +'/status/',
    'https://web.archive.org/web/*/https://twitter.com/'+ x +'/status/*',
    'http://uid.me/' + x,
    'https://account.venmo.com/u/' + x,
    'https://www.wattpad.com/user/' + x,
    'https://profiles.wordpress.org/' + x,
    'https://www.xboxgamertag.com/search/' + x,
    'https://www.youtube.com/user/'+ x +'/videos',
    'https://cracked.io/' + x,
    'https://altenens.is/memebers/' + x,
    'https://www.crunchyroll.com/user/' + x,
    }

    for url in urls:
        check_url(url)

    with open("success_urls.txt", "a") as success_file:
        success_file.write(url + "\n")

            # Start a separate thread for each URL
    threads = [threading.Thread(target=check_url, args=(url,)) for url in urls]
    for thread in threads:
        thread.start()

# Wait for all threads to finish
    for thread in threads:
        thread.join()

    print("Reset\n")
